name: pixel_adventure
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flame: ^1.8.2
  flame_tiled: ^1.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/images/Terrain/
    - assets/images/Background/
    - assets/images/HUD/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Items/Fruits/
    - assets/images/Traps/Saw/
    - assets/images/Items/Checkpoints/Checkpoint/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 